formatter: markdown

content: |-
  ## Usage
  ```hcl
  {{ include "examples/basic/main.tf" }}
  ```
  {{ .Requirements }}
  {{ .Providers }}
  {{ .Modules }}
  {{ .Resources }}
  {{ .Inputs }}
  {{ .Outputs }}

output:
  file: README.md
  mode: replace
  template: |-
    # terraform-aws-ec2-k8s-resources

    A simple Terraform module which returns a k8s resources requests/limits for a given instance type.

    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

    ## License
    The Apache-2.0 license

sort:
  enabled: true
  by: required

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  required: true
  sensitive: true
  type: true
